### ISSUE TITLE
Support tabs in addition to spaces in config file

### ISSUE THREAD

**Issue by rholveck** [sentriz/flagconf#1]
https://github.com/sentriz/flagconf/blob/9fe528a80ff4365ab2fcb24c87c671c2667c0d3b/flagconf.go#L163C48-L163C52

Hi ! It would be great to be able to use tabs in addition to spaces in the config file.

Right now if one uses tabs between key and value it fail silently. Had the issue in Gonic.

What do you think ?

**Comment by sentriz** [comment]
i think this makes sense. that said, i don't belive it was supported in previous versions of gonic either? https://github.com/peterbourgon/ff/blob/main/parse.go#L233

**Comment by rholveck** [comment]
I guess I wasn't :) But I started using Gonic only a few weeks ago so I only used the version with flagconf.

**Comment by sentriz** [comment]
ah i see :+1:

**Comment by rholveck** [comment]
Tested in Gonic : works fine :) Thanks !
